#! /bin/sh

sxhkd &

bspc config border_width        1
bspc config window_gap          8

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer   true
bspc config focused_border_color '#770000'
bspc config right_padding 0
bspc config left_padding 0
bspc config bottom_padding 0

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

panel &
