#! /bin/sh

sxhkd &

bspc config border_width        1
bspc config window_gap          8

bspc config split_ratio         0.50
bspc config borderless_monocle  false
bspc config gapless_monocle     false
bspc config focus_by_distance   true
bspc config focus_follows_pointer   true
bspc config focused_border_color '#770000'
bspc config presel_feedback_color '#101010'
bspc config right_padding -8
bspc config left_padding -8
bspc config bottom_padding -8
bspc config top_padding -8

bspc monitor -d 1 2 3 4 5 6 7 8 9

#bspc rule -a mpv state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
#bspc rule -a scratchpad sticky=on state=floating
urxvt &
